services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - redis
#  memcached:
#    image: memcached
#    command:
#      - '-m 64'
#    ports:
#      - "11211:11211"
  redis:
    image: redis
    restart: always
    volumes:
      - ./data/redis:/data
#    command: redis-server /usr/local/etc/redis/redis.conf
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./data:/data
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      - "80:80"